// AUTO-GENERATED by scripts/build-bases.ts. Do not edit by hand.
// Source: packages/themes/medieval-fantasy/src/subjects/_assets/axe-head-*.svg

export const axeHeadBases: readonly string[] = [
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <rect x="28" y="6" width="6" height="54" fill="{{secondary}}"/>
    <path d="M34,12 L52,16 L52,30 L34,28 Z" fill="{{primary}}"/>
    <line x1="34" y1="20" x2="48" y2="22" stroke="{{accent}}" stroke-width="2"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <rect x="28" y="8" width="6" height="50" fill="{{secondary}}"/>
    <path d="M34,12 L56,18 L56,30 L34,26 Z" fill="{{primary}}"/>
    <path d="M28,18 L14,16 L10,28 L28,28 Z" fill="{{primary}}"/>
    <line x1="36" y1="20" x2="52" y2="22" stroke="{{accent}}" stroke-width="2"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <rect x="28" y="6" width="6" height="54" fill="{{secondary}}"/>
    <path d="M34,12 L52,18 L52,28 L34,26 Z" fill="{{primary}}"/>
    <path d="M28,18 L14,14 L10,18 L20,22 L28,22 Z" fill="{{accent}}"/>
    <line x1="36" y1="20" x2="48" y2="22" stroke="{{neutral}}" stroke-width="2"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <rect x="28" y="6" width="6" height="54" fill="{{secondary}}"/>
    <path d="M34,10 L50,14 L54,30 L44,42 L34,40 Z" fill="{{primary}}"/>
    <line x1="36" y1="22" x2="48" y2="26" stroke="{{accent}}" stroke-width="2"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <rect x="28" y="22" width="6" height="36" fill="{{secondary}}"/>
    <path d="M34,18 L50,22 L48,32 L34,30 Z" fill="{{primary}}"/>
    <line x1="36" y1="24" x2="46" y2="26" stroke="{{accent}}" stroke-width="2"/>
  </g>`,
] as const;
