// AUTO-GENERATED by scripts/build-bases.ts. Do not edit by hand.
// Source: packages/themes/medieval-fantasy/src/subjects/_assets/axe-head-*.svg

export const axeHeadBases: readonly string[] = [
  `<g>
    <line x1="32" y1="8" x2="32" y2="56" stroke="{{neutral}}" stroke-width="4" stroke-linecap="round"/>
    <path d="M32,14 L48,18 L48,28 L32,32 Z" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2"/>
    <line x1="48" y1="18" x2="48" y2="28" stroke="{{accent}}" stroke-width="1.5"/>
  </g>`,
  `<g>
    <line x1="32" y1="8" x2="32" y2="56" stroke="{{neutral}}" stroke-width="4" stroke-linecap="round"/>
    <path d="M32,14 L48,18 L48,28 L32,30 Z" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2"/>
    <path d="M32,16 L20,20 L20,26 L32,28 Z" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2"/>
  </g>`,
  `<g>
    <line x1="32" y1="10" x2="32" y2="54" stroke="{{neutral}}" stroke-width="4" stroke-linecap="round"/>
    <path d="M32,14 L48,18 L48,28 L32,30 Z" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2"/>
    <path d="M32,18 L18,22 L18,24 L32,26 Z" fill="{{accent}}" stroke="{{neutral}}" stroke-width="2"/>
  </g>`,
  `<g>
    <line x1="32" y1="8" x2="32" y2="56" stroke="{{neutral}}" stroke-width="4" stroke-linecap="round"/>
    <path d="M32,12 L46,14 L48,22 L48,32 L40,40 L32,38 Z" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2"/>
  </g>`,
  `<g>
    <line x1="32" y1="22" x2="32" y2="54" stroke="{{neutral}}" stroke-width="4" stroke-linecap="round"/>
    <path d="M32,22 L46,24 L46,34 L32,36 Z" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2"/>
    <line x1="46" y1="24" x2="46" y2="34" stroke="{{accent}}" stroke-width="1"/>
  </g>`,
] as const;
