// AUTO-GENERATED by scripts/build-bases.ts. Do not edit by hand.
// Source: packages/themes/medieval-fantasy/src/subjects/_assets/potion-bottle-*.svg

export const potionBottleBases: readonly string[] = [
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <path d="M26,8 L38,8 L38,22 Q50,32 50,46 Q50,58 32,58 Q14,58 14,46 Q14,32 26,22 Z" fill="{{primary}}"/>
    <path d="M14,46 Q32,40 50,46" stroke="{{accent}}" stroke-width="2" fill="none"/>
    <rect x="24" y="4" width="16" height="6" fill="{{secondary}}"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <path d="M28,12 L36,12 L36,26 Q40,28 40,32 L40,54 Q40,60 32,60 Q24,60 24,54 L24,32 Q24,28 28,26 Z" fill="{{primary}}"/>
    <path d="M24,40 L40,40" stroke="{{accent}}" stroke-width="2"/>
    <rect x="26" y="6" width="12" height="6" fill="{{secondary}}"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <path d="M28,14 L36,14 L36,22 Q52,30 52,44 Q52,58 32,58 Q12,58 12,44 Q12,30 28,22 Z" fill="{{primary}}"/>
    <path d="M12,40 Q22,34 32,40 Q42,46 52,40" stroke="{{accent}}" stroke-width="2" fill="none"/>
    <circle cx="22" cy="46" r="2" fill="{{accent}}"/>
    <circle cx="40" cy="50" r="2" fill="{{accent}}"/>
    <rect x="26" y="8" width="12" height="6" fill="{{secondary}}"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <path d="M26,14 L38,14 L38,22 L48,28 L48,56 Q48,58 46,58 L18,58 Q16,58 16,56 L16,28 L26,22 Z" fill="{{primary}}"/>
    <rect x="20" y="36" width="24" height="10" fill="{{accent}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="22" y="6" width="20" height="8" fill="{{secondary}}"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <path d="M28,10 L36,10 L36,16 Q44,20 44,26 Q44,32 36,34 Q50,38 50,48 Q50,58 32,58 Q14,58 14,48 Q14,38 28,34 Q20,32 20,26 Q20,20 28,16 Z" fill="{{primary}}"/>
    <circle cx="22" cy="48" r="2" fill="{{accent}}"/>
    <circle cx="32" cy="52" r="2" fill="{{accent}}"/>
    <circle cx="42" cy="48" r="2" fill="{{accent}}"/>
    <rect x="26" y="4" width="12" height="6" fill="{{secondary}}"/>
  </g>`,
] as const;
