// AUTO-GENERATED by scripts/build-bases.ts. Do not edit by hand.
// Source: packages/themes/medieval-fantasy/src/subjects/_assets/potion-bottle-*.svg

export const potionBottleBases: readonly string[] = [
  `<g>
    <rect x="27" y="6" width="10" height="4" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="28" y="10" width="8" height="10" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <path d="M24,20 L40,20 L52,54 L12,54 Z" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <line x1="16" y1="42" x2="48" y2="42" stroke="{{accent}}" stroke-width="1"/>
  </g>`,
  `<g>
    <rect x="27" y="4" width="10" height="4" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="28" y="8" width="8" height="14" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <circle cx="32" cy="42" r="16" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <circle cx="28" cy="40" r="1.5" fill="{{accent}}"/>
    <circle cx="36" cy="46" r="1.5" fill="{{accent}}"/>
  </g>`,
  `<g>
    <rect x="28" y="4" width="8" height="2" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="29" y="6" width="6" height="8" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="25" y="14" width="14" height="42" rx="4" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <line x1="26" y1="30" x2="38" y2="30" stroke="{{accent}}" stroke-width="1"/>
  </g>`,
  `<g>
    <rect x="22" y="8" width="20" height="8" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <path d="M22,22 L26,16 L38,16 L42,22 Z" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="18" y="22" width="28" height="34" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <rect x="22" y="32" width="20" height="10" fill="none" stroke="{{accent}}" stroke-width="1"/>
  </g>`,
  `<g>
    <rect x="28" y="8" width="8" height="4" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="29" y="12" width="6" height="4" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <ellipse cx="32" cy="46" rx="14" ry="10" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <ellipse cx="32" cy="24" rx="10" ry="8" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <rect x="29" y="29" width="6" height="8" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <circle cx="28" cy="46" r="1.2" fill="{{accent}}"/>
    <circle cx="32" cy="50" r="1.2" fill="{{accent}}"/>
    <circle cx="36" cy="46" r="1.2" fill="{{accent}}"/>
  </g>`,
] as const;
