// AUTO-GENERATED by scripts/build-bases.ts. Do not edit by hand.
// Source: packages/themes/medieval-fantasy/src/subjects/_assets/scroll-roll-*.svg

export const scrollRollBases: readonly string[] = [
  `<g>
    <rect x="14" y="14" width="36" height="36" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <ellipse cx="32" cy="14" rx="18" ry="4" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <ellipse cx="32" cy="50" rx="18" ry="4" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <line x1="18" y1="26" x2="46" y2="26" stroke="{{accent}}" stroke-width="1"/>
    <line x1="18" y1="38" x2="46" y2="38" stroke="{{accent}}" stroke-width="1"/>
  </g>`,
  `<g>
    <rect x="14" y="14" width="36" height="36" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <ellipse cx="32" cy="14" rx="18" ry="4" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <ellipse cx="32" cy="50" rx="18" ry="4" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <line x1="18" y1="22" x2="46" y2="22" stroke="{{accent}}" stroke-width="1.5"/>
    <line x1="18" y1="30" x2="46" y2="30" stroke="{{accent}}" stroke-width="1.5"/>
    <line x1="18" y1="38" x2="46" y2="38" stroke="{{accent}}" stroke-width="1.5"/>
  </g>`,
  `<g>
    <rect x="18" y="12" width="28" height="36" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <ellipse cx="32" cy="12" rx="14" ry="3" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <path d="M18,48 Q14,52 14,56 L20,56 Q24,52 24,48 Z" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <path d="M46,48 Q50,52 50,56 L44,56 Q40,52 40,48 Z" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <line x1="22" y1="24" x2="42" y2="24" stroke="{{accent}}" stroke-width="1"/>
    <line x1="22" y1="34" x2="42" y2="34" stroke="{{accent}}" stroke-width="1"/>
  </g>`,
  `<g>
    <rect x="12" y="20" width="40" height="24" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <ellipse cx="12" cy="32" rx="4" ry="14" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <ellipse cx="52" cy="32" rx="4" ry="14" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <line x1="24" y1="24" x2="24" y2="40" stroke="{{accent}}" stroke-width="1"/>
    <line x1="40" y1="24" x2="40" y2="40" stroke="{{accent}}" stroke-width="1"/>
  </g>`,
  `<g>
    <rect x="14" y="14" width="36" height="36" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <ellipse cx="32" cy="14" rx="18" ry="4" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <ellipse cx="32" cy="50" rx="18" ry="4" fill="{{secondary}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="10" y="30" width="44" height="4" fill="{{accent}}" stroke="{{neutral}}" stroke-width="1.5"/>
  </g>`,
] as const;
