// AUTO-GENERATED by scripts/build-bases.ts. Do not edit by hand.
// Source: packages/themes/medieval-fantasy/src/subjects/_assets/shield-frame-*.svg

export const shieldFrameBases: readonly string[] = [
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <path d="M14,10 Q14,8 16,8 L48,8 Q50,8 50,10 L50,32 Q50,48 32,58 Q14,48 14,32 Z" fill="{{primary}}"/>
    <path d="M32,8 L32,58" stroke="{{accent}}" stroke-width="2"/>
    <path d="M14,20 L50,20" stroke="{{secondary}}" stroke-width="2"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <path d="M32,6 Q46,8 48,18 Q44,42 32,60 Q20,42 16,18 Q18,8 32,6 Z" fill="{{primary}}"/>
    <circle cx="32" cy="22" r="4" fill="{{accent}}"/>
    <path d="M32,26 L32,50" stroke="{{secondary}}" stroke-width="2"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <circle cx="32" cy="32" r="26" fill="{{primary}}"/>
    <circle cx="32" cy="32" r="18" stroke="{{secondary}}" stroke-width="2"/>
    <circle cx="32" cy="32" r="6" fill="{{accent}}"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <path d="M12,6 L52,6 L52,50 Q52,58 32,60 Q12,58 12,50 Z" fill="{{primary}}"/>
    <path d="M32,6 L32,60" stroke="{{secondary}}" stroke-width="2"/>
    <path d="M12,18 L52,18" stroke="{{accent}}" stroke-width="2"/>
    <path d="M12,42 L52,42" stroke="{{accent}}" stroke-width="2"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <path d="M12,8 L52,8 L52,30 Q52,48 32,60 Q12,48 12,30 Z" fill="{{primary}}"/>
    <path d="M32,14 L32,52" stroke="{{accent}}" stroke-width="3"/>
    <path d="M16,22 L48,22" stroke="{{accent}}" stroke-width="3"/>
    <circle cx="32" cy="22" r="3" fill="{{secondary}}"/>
  </g>`,
] as const;
