// AUTO-GENERATED by scripts/build-bases.ts. Do not edit by hand.
// Source: packages/themes/medieval-fantasy/src/subjects/_assets/shield-frame-*.svg

export const shieldFrameBases: readonly string[] = [
  `<g>
    <path d="M16,12 Q16,8 20,8 L44,8 Q48,8 48,12 L48,38 Q48,56 32,56 Q16,56 16,38 Z" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <line x1="16" y1="28" x2="48" y2="28" stroke="{{accent}}" stroke-width="1"/>
  </g>`,
  `<g>
    <circle cx="32" cy="32" r="24" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <circle cx="32" cy="32" r="18" fill="none" stroke="{{neutral}}" stroke-width="2"/>
    <circle cx="32" cy="32" r="5" fill="{{accent}}" stroke="{{neutral}}" stroke-width="2"/>
  </g>`,
  `<g>
    <path d="M18,12 Q18,8 22,8 L42,8 Q46,8 46,12 L46,22 Q46,40 32,58 Q18,40 18,22 Z" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <line x1="32" y1="14" x2="32" y2="52" stroke="{{accent}}" stroke-width="1"/>
  </g>`,
  `<g>
    <path d="M16,12 Q16,8 20,8 L44,8 Q48,8 48,12 L48,38 Q48,56 32,56 Q16,56 16,38 Z" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <polyline points="20,24 32,36 44,24" fill="none" stroke="{{accent}}" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>
  </g>`,
  `<g>
    <path d="M16,12 Q16,8 20,8 L44,8 Q48,8 48,12 L48,38 Q48,56 32,56 Q16,56 16,38 Z" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2.5"/>
    <line x1="32" y1="12" x2="32" y2="52" stroke="{{accent}}" stroke-width="3"/>
    <line x1="16" y1="24" x2="48" y2="24" stroke="{{accent}}" stroke-width="3"/>
  </g>`,
] as const;
