// AUTO-GENERATED by scripts/build-bases.ts. Do not edit by hand.
// Source: packages/themes/medieval-fantasy/src/subjects/_assets/sword-blade-*.svg

export const swordBladeBases: readonly string[] = [
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <polygon points="32,5 36,11 36,37 28,37 28,11" fill="{{primary}}"/>
    <rect x="18" y="37" width="28" height="4" fill="{{secondary}}"/>
    <rect x="29" y="41" width="6" height="13" fill="{{primary}}"/>
    <circle cx="32" cy="56" r="3" fill="{{accent}}"/>
    <line x1="32" y1="11" x2="32" y2="36" stroke-width="1"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <polygon points="32,6 39,16 39,34 25,34 25,16" fill="{{primary}}"/>
    <path d="M16,40 L20,34 L44,34 L48,40 Z" fill="{{secondary}}"/>
    <rect x="29" y="40" width="6" height="11" fill="{{primary}}"/>
    <ellipse cx="32" cy="54" rx="5" ry="4" fill="{{accent}}"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <path d="M48,8 Q26,16 24,40 L30,40 Q32,20 52,12 Z" fill="{{primary}}"/>
    <rect x="16" y="40" width="22" height="4" fill="{{secondary}}"/>
    <rect x="24" y="44" width="6" height="10" fill="{{primary}}"/>
    <circle cx="27" cy="55" r="4" fill="{{accent}}"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <polygon points="32,4 36,9 36,33 28,33 28,9" fill="{{primary}}"/>
    <line x1="32" y1="11" x2="32" y2="31" stroke-width="2"/>
    <path d="M14,33 L20,38 L44,38 L50,33 L46,40 L18,40 Z" fill="{{secondary}}"/>
    <rect x="30" y="40" width="4" height="13" fill="{{primary}}"/>
    <path d="M28,53 Q32,47 36,53 Q34,59 32,59 Q30,59 28,53 Z" fill="{{accent}}"/>
  </g>`,
  `<g fill="none" stroke="{{neutral}}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
    <polygon points="32,5 34,10 34,38 30,38 30,10" fill="{{primary}}"/>
    <rect x="20" y="38" width="24" height="3" fill="{{secondary}}"/>
    <path d="M22,41 Q16,46 22,50" stroke-width="2"/>
    <path d="M42,41 Q48,46 42,50" stroke-width="2"/>
    <rect x="30" y="41" width="4" height="11" fill="{{primary}}"/>
    <circle cx="32" cy="55" r="4" fill="{{accent}}"/>
  </g>`,
] as const;
