// AUTO-GENERATED by scripts/build-bases.ts. Do not edit by hand.
// Source: packages/themes/medieval-fantasy/src/subjects/_assets/sword-blade-*.svg

export const swordBladeBases: readonly string[] = [
  `<g>
    <rect x="29" y="8" width="6" height="36" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="20" y="44" width="24" height="3" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="29.5" y="47" width="5" height="8" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <circle cx="32" cy="57" r="2.5" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <line x1="32" y1="10" x2="32" y2="42" stroke="{{accent}}" stroke-width="1"/>
  </g>`,
  `<g>
    <polygon points="32,8 40,40 24,40" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="18" y="40" width="28" height="3" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="29.5" y="43" width="5" height="10" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <circle cx="32" cy="56" r="3.5" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
  </g>`,
  `<g>
    <rect x="29.5" y="10" width="5" height="22" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="24" y="32" width="16" height="3" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="29.5" y="35" width="5" height="12" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <circle cx="32" cy="51" r="4" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <polygon points="32,48 34,51 32,54 30,51" fill="{{accent}}"/>
  </g>`,
  `<g>
    <rect x="28.5" y="6" width="7" height="32" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="17" y="38" width="30" height="3" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <rect x="29.5" y="41" width="5" height="14" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <ellipse cx="32" cy="57" rx="4" ry="3" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <line x1="32" y1="10" x2="32" y2="37" stroke="{{accent}}" stroke-width="1"/>
  </g>`,
  `<g>
    <polygon points="13.41,53.41 53.41,13.41 50.59,10.59 10.59,50.59" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2"/>
    <polygon points="50.59,53.41 53.41,50.59 13.41,10.59 10.59,13.41" fill="{{primary}}" stroke="{{neutral}}" stroke-width="2"/>
    <polygon points="28.87,40.79 27.45,42.21 21.79,36.55 23.21,35.13" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
    <polygon points="35.13,40.79 36.55,42.21 42.21,36.55 40.79,35.13" fill="{{neutral}}" stroke="{{neutral}}" stroke-width="2"/>
  </g>`,
] as const;
