import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

interface BaseGroup {
  subject: string;
  files: { path: string; content: string; index: number }[];
}

const THEME_ROOT = 'packages/themes/medieval-fantasy/src/subjects';
const ASSETS_DIR = join(THEME_ROOT, '_assets');

const ROLE_TOKENS = ['{{primary}}', '{{secondary}}', '{{accent}}', '{{neutral}}'];

function validate(filename: string, svg: string): void {
  if (!/^[\x00-\x7F]*$/.test(svg)) throw new Error(`${filename}: non-ASCII characters`);
  if (!svg.includes('viewBox="0 0 64 64"')) throw new Error(`${filename}: missing viewBox="0 0 64 64"`);
  if (svg.includes('<image')) throw new Error(`${filename}: contains <image>`);
  if (svg.includes('<script')) throw new Error(`${filename}: contains <script>`);
  if (svg.includes('<style')) throw new Error(`${filename}: contains <style>`);
  if (svg.includes('xlink:href')) throw new Error(`${filename}: contains external xlink:href`);
  // require at least one palette token; warn (not fail) if none
  const hasToken = ROLE_TOKENS.some((t) => svg.includes(t));
  if (!hasToken) console.warn(`${filename}: no palette tokens — base will render with no palette substitution`);
}

function extractBody(svg: string): string {
  // Strip <svg ...> wrapper — keep contents as-is.
  const open = svg.match(/<svg[^>]*>/);
  if (!open) throw new Error('no <svg> open tag');
  const close = svg.lastIndexOf('</svg>');
  if (close === -1) throw new Error('no </svg> close tag');
  const body = svg.slice(open.index! + open[0].length, close).trim();
  if (!body.startsWith('<g')) throw new Error('body does not start with single <g> root');
  return body;
}

function escapeForTemplateLiteral(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function groupFiles(): BaseGroup[] {
  if (!existsSync(ASSETS_DIR)) {
    console.log(`No _assets dir at ${ASSETS_DIR} — skipping`);
    return [];
  }
  const files = readdirSync(ASSETS_DIR).filter((f) => f.endsWith('.svg')).sort();
  const groups = new Map<string, BaseGroup>();
  for (const f of files) {
    const m = f.match(/^(.+)-(\d+)\.svg$/);
    if (!m) throw new Error(`${f}: filename must be <subject>-<index>.svg`);
    const subject = m[1] as string;
    const idx = Number(m[2]);
    const content = readFileSync(join(ASSETS_DIR, f), 'utf8');
    validate(f, content);
    const body = extractBody(content);
    if (!groups.has(subject)) groups.set(subject, { subject, files: [] });
    groups.get(subject)!.files.push({ path: f, content: body, index: idx });
  }
  return [...groups.values()].map((g) => ({
    subject: g.subject,
    files: g.files.sort((a, b) => a.index - b.index),
  }));
}

function writeModule(group: BaseGroup): void {
  const exportName = group.subject.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()) + 'Bases';
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by scripts/build-bases.ts. Do not edit by hand.');
  lines.push(`// Source: packages/themes/medieval-fantasy/src/subjects/_assets/${group.subject}-*.svg`);
  lines.push('');
  lines.push(`export const ${exportName}: readonly string[] = [`);
  for (const f of group.files) {
    lines.push(`  \`${escapeForTemplateLiteral(f.content)}\`,`);
  }
  lines.push('] as const;');
  lines.push('');
  const out = join(THEME_ROOT, `${group.subject}.bases.ts`);
  writeFileSync(out, lines.join('\n'), 'utf8');
  console.log(`wrote ${out} (${group.files.length} bases)`);
}

function main(): void {
  const groups = groupFiles();
  if (groups.length === 0) {
    console.log('No base groups found. Exiting.');
    return;
  }
  for (const g of groups) writeModule(g);
  console.log(`build-bases: ${groups.length} subject groups, ${groups.reduce((n, g) => n + g.files.length, 0)} bases total.`);
}

main();
